modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
issueTrackerURL="https://github.com/GustavoSasaki/Ragnarok-Cards/issues"
logoFile="logo.png"


[[mods]]
modId="ragnarok_cards"
version="1.16.4-1.2"
displayName="Ragnarok Cards"
updateJSONURL="https://raw.githubusercontent.com/GustavoSasaki/Ragnarok-Cards/update_checker/update.json"
displayURL="https://github.com/GustavoSasaki/Ragnarok-Cards"
credits='''
Programmer: Gustavo Sasaki (TheAgent00g)
Artist: trillium109, Pepson
Special Thanks: dirtis1979, koffekid
'''

description='''
This Minecraft Mod adds a new type of equipment, the Ragnarok Cards, which expands the number of possible builds, and makes viable multiple specialization,
Such as in ranged weapons or applying negative effects on the enemy or even being really good at killing pigs.'''

[[dependencies.ragnarok_cards]] #optional
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ragnarok_cards]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.17)"
    ordering="NONE"
    side="BOTH"
