
modLoader="javafml"
loaderVersion="[35,)"
license="MIT"

issueTrackerURL="https://github.com/GustavoSasaki/Ragnarok-Cards/issues"
updateJSONURL="https://github.com/GustavoSasaki/Ragnarok-Cards/raw/master/update.json"

[[mods]]
modId="ragnarok_cards"
version="1.16.4-0.0.8"
displayName="Ragnarok Cards"

updateJSONURL="https://github.com/GustavoSasaki/Ragnarok-Cards"
displayURL="https://github.com/GustavoSasaki/Ragnarok-Cards"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional

credits='''Programmer:Gustavo Sasaki (TheAgente00g)
Artist: trillium109, Pepson
'''
#authors="Gustavo Sasaki (TheAgent00g)" #optional
description='''
This mod adds the Ragnarok Cards, they are items, which when in the upper row of player inventory gives a variety of combat buffs and debuffs.
Every card is dropped by a unique vanilla mob with a really low chance.'''

[[dependencies.ragnarok_cards]] #optional
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ragnarok_cards]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
